---
title: "camden_maps"
format: html
---

```{r load data}

library(tidyverse)
library(ggplot2)
library(leaflet)
library(leaflet.extras)
library(readr)
library(sf)
library(here)
library(dplyr)
library(tidycensus)
census_api_key("0702f85699449016b5b9de6482e5cc397e53b3fe", overwrite = TRUE)

current_directory <- setwd("~/Desktop/Spring 2024/R DATA VIZ/GLHLTH562/FinalProject")

camden_og <- read_csv("~/Desktop/Spring 2024/R DATA VIZ/GLHLTH562/FinalProject/data/nj_camden_2020_04_01.csv")

```

```{r filtered}

camden_bounds <- c(lat_min = 39.875, lat_max = 39.961,
                   lng_min = -75.137, lng_max = -75.045)

filtered_camden <- camden_og |> 
  filter(!is.na(lat) & !is.na(lng)) |> 
  filter(lat >= camden_bounds["lat_min"] & lat <= camden_bounds["lat_max"] &
         lng >= camden_bounds["lng_min"] & lng <= camden_bounds["lng_max"])

view(filtered_camden)

camden <- filtered_camden |> 
  subset(type == "vehicular")


sampled_camden <- camden |> 
  sample_n(100)

```

```{r test maps}

#HEATMAP
leaflet(camden) |> 
  addTiles() |> 
  addHeatmap(~lng, ~lat)

#dots
leaflet(camden) |> 
  addTiles() |> 
  addCircleMarkers(lng = ~lng, lat = ~lat, radius = 5, fillOpacity = 0.5)

#dots by racial groupings
driver_black <- subset(camden, subject_race == "black")
view(driver_black)

leaflet(driver_black) |> 
  addTiles() |> 
  addCircleMarkers(lng = ~lng, lat = ~lat, radius = 0.25, fillOpacity = 0.25)


```

```{r census}

#sample map by median household income
camden_income <- get_acs(geography = "tract",
                         variables = "B06011_001",
                         state = "NJ",
                         county = "Camden",
                         geometry = TRUE)


ggplot() +
  geom_sf(data = camden_income, aes(fill = estimate)) +
  theme_minimal() +
  labs(title = "Median Household Income in Camden County, NJ",
       fill = "Median Income")

camden_white <- get_decennial(geography = "tract",
                              variables = "P1_003N",
                              state = "NJ",
                              county = "Camden",
                              geometry = TRUE) 

ggplot() +
  geom_sf(data = camden_white, aes(fill = value)) +
  theme_minimal() +
  labs(title = "White Population in Camden County, NJ",
       fill = "White Population Estimate")

camden_black <- get_decennial(geography = "tract",
                              variables = "P1_004N",
                              state = "NJ",
                              county = "Camden",
                              geometry = TRUE)

ggplot() +
  geom_sf(data = camden_black, aes(fill = value)) +
  theme_minimal() +
  labs(title = "Black Population in Camden County, NJ",
       fill = "Black Population Estimate")

camden_asian <- get_decennial(geography = "tract",
                              variables = "P1_006N",
                              state = "NJ",
                              county = "Camden",
                              geometry = TRUE)

ggplot() +
  geom_sf(data = camden_black, aes(fill = value)) +
  theme_minimal() +
  labs(title = "Asian Population in Camden County, NJ",
       fill = "Asian Population Estimate")

```

```{r census data}

options(tigris_use_cache = TRUE)

race_variables <- load_variables(2020, "pl", cache = TRUE)
view(race_variables)

#P1_003N white only
#P1_004N black only
# P1_006N asian only

income_variables <- load_variables(2020, "acs5")
view(income_variables)

#B06011_001 median income in the last 12 months

```

```{r tract test}

library(mapview)
library(tigris) 

camden_tracts <- tracts("NJ", "Camden")
mapview(camden_tracts)

tracts_to_include <- c(600200, 600400, 600700, 600800, 600900, 601000, 601101, 
                       601102, 601200, 601300, 601400, 601500, 601600, 601700, 
                       601800, 601900, 602000, 610300, 610400)

camden_tracts_subset <- camden_tracts[camden_tracts$TRACT %in% tracts_to_include, ]

mapview(camden_tracts_subset)


```
